### ISSUE TITLE
Fill in a lookup field based on the record fields WITH workflow

### ISSUE THREAD

**Issue by hrhgl** [a33ik/UltimateWorkflowToolkit#33]
Hello dear Andrew 
Hope you are well.

First of all I have to thank you for the solution you wrote. (UWT)

I have a problem and I wanted to fix this with UWT.

I want to fill in a lookup field based on the record fields WITH workflow.

But you have published little manual for this purpose. Can you help me out in a friendly way?

**Comment by hamidghouli** [comment]
any update?

**Comment by AndrewButenko** [comment]
Hello, I live at the US (and it is 7:30AM now when I write this reply) and I don't work during the weekend so I'm sorry for the late reply.
Can you please extend your description because it is too vague. I see scenarios where there is no need in my UWT to make it possible via workflows so I need more context to understand yours scenario.
Andrew

**Comment by hrhgl** [comment]
Thank you for your response.
I guess the scenario I needed is already at UWT but I can't find it ...

The scenario is as follows:

I have a custom entity ("X") that contains the following fields: (with Many records)
field "XA"
field "XB"
field "XC"

And I also have a custom entity ("Y") that contains the following fields: (with Many records)
field "YA"
field "YB"
field "YC"

(and field values are same in Y and X  for same records)
The two entities have had no relationship but recently I create a relationship between them ( "X" is parent of "Y")

and I want to connect all child records to parent with lookup field "YAA"

I need a solution to automatically fill lookup field "YAA" for all records of entity "Y" by workflow , base on field "YA", field "YB", field "YC" values . ( I can do this manually or by JS on form loading)

this solution do exactly what i need , but it is not compatible with Version 1612 (9.0.8.9) (DB 9.0.8.9) on-premises:
https://www.itaintboring.com/dynamics-crm/dynamics-crm-use-a-workflow-to-set-a-lookup/

**Comment by AndrewButenko** [comment]
I believe it's possible to do what you described using my toolkit.
In order to do that perform following steps:

Create on-demand workflow for your X entity.
Using advanced find build FetchXml query that will query records of Y type based on value of fields YA, YB, YC.
Using String Combine step, FetchXml you prepared on the previous step and values from fields of XA, XB and XC construct query.
Using "Add Lookup to request" action and reference to your current record X. Use schema name of lookup for a field name.
Use Update Records action, pass combined FetchXml to "FetchXml" parameter and Request as a request you combined on the previous step.
Save and publish workflow.
Distribute workflow on the set of all "Y" records.
